import json
from pathlib import Path
from datetime import datetime
from src.utils import app_logger

class ExportGenerator:
    def __init__(self):
        self.export_dir = Path.home() / ".reaper_audio_enhancement" / "exports"
        self.export_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_export(self, project_data):
        """
        Generate export instructions for REAPER.
        project_data: dict with analysis and suggestions
        """
        try:
            export_data = {
                "timestamp": datetime.now().isoformat(),
                "version": "0.1.0",
                "audio_track": {
                    "name": "Original Audio",
                    "type": "audio",
                    "file": project_data.get("audio_file"),
                    "processing": {
                        "noise_reduction": {
                            "enabled": True,
                            "strength": project_data.get("noise_reduction_strength", 0.5),
                            "output_file": project_data.get("processed_audio_file"),
                        }
                    }
                },
                "video_track": {
                    "name": "Video",
                    "type": "video",
                    "file": project_data.get("video_file"),
                },
                "enhancement_tracks": [],
                "suggestions": project_data.get("suggestions", []),
            }
            
            for i, suggestion in enumerate(project_data.get("suggestions", [])):
                if suggestion.get("accepted", False):
                    track = {
                        "name": f"Enhancement - {suggestion['scene']}",
                        "type": "audio",
                        "file": suggestion.get("audio_path"),
                        "start_time": suggestion.get("start_time", 0),
                        "duration": suggestion.get("duration"),
                        "volume": 1.0 - suggestion.get("volume_reduction", 0.3),
                        "fade_in": suggestion.get("fade_in", 0.5),
                        "fade_out": suggestion.get("fade_out", 0.5),
                    }
                    export_data["enhancement_tracks"].append(track)
            
            filename = f"export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
            export_path = self.export_dir / filename
            
            with open(export_path, 'w') as f:
                json.dump(export_data, f, indent=2)
            
            app_logger.info(f"Export generated: {export_path}")
            return export_path
        except Exception as e:
            app_logger.error(f"Error generating export: {e}")
            return None
    
    def generate_reaper_script(self, export_file):
        """
        Generate REAPER ReaScript (Python) for importing results.
        """
        try:
            with open(export_file, 'r') as f:
                export_data = json.load(f)
            
            script = self._create_reaper_script(export_data)
            
            script_path = self.export_dir / f"{export_file.stem}_import.py"
            
            with open(script_path, 'w') as f:
                f.write(script)
            
            app_logger.info(f"REAPER script generated: {script_path}")
            return script_path
        except Exception as e:
            app_logger.error(f"Error generating REAPER script: {e}")
            return None
    
    def _create_reaper_script(self, export_data):
        """
        Create REAPER ReaScript content.
        """
        script = '''#!/usr/bin/env python3
# REAPER Audio Enhancement Import Script
# Auto-generated by Audio Enhancement Tool

import json

def main():
    """Import audio enhancement results into REAPER."""
    
    # Get current project
    project = RPR_EnumProjects(-1)
    
    # Create audio track
    RPR_InsertTrackAtIndex(0, False)
    audio_track = RPR_GetTrack(project, 0)
    RPR_GetSetMediaTrackInfo_String(audio_track, "P_NAME", "Original Audio", True)
    
    # Create video track
    RPR_InsertTrackAtIndex(1, False)
    video_track = RPR_GetTrack(project, 1)
    RPR_GetSetMediaTrackInfo_String(video_track, "P_NAME", "Video", True)
    
    # Add enhancement tracks
    for i, track_info in enumerate(enhancement_tracks):
        RPR_InsertTrackAtIndex(i + 2, False)
        track = RPR_GetTrack(project, i + 2)
        RPR_GetSetMediaTrackInfo_String(track, "P_NAME", track_info["name"], True)
    
    # Refresh UI
    RPR_UpdateArrange()

if __name__ == "__main__":
    main()
'''
        return script
