import json
from pathlib import Path
from src.utils import app_logger


class ReaScriptImporter:
    """
    Generate and manage REAPER ReaScript for importing audio enhancement results.
    """
    
    def __init__(self):
        self.export_dir = Path.home() / ".reaper_audio_enhancement" / "exports"
        self.export_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_reascript(self, export_data):
        """
        Generate complete REAPER ReaScript (Python) from export data.
        """
        try:
            script = self._create_reaper_script(export_data)
            return script
        except Exception as e:
            app_logger.error(f"Error generating ReaScript: {e}")
            return None
    
    def save_reascript(self, export_data, output_path=None):
        """
        Generate and save ReaScript to file.
        """
        try:
            script = self.generate_reascript(export_data)
            if not script:
                return None
            
            if output_path is None:
                timestamp = export_data.get("timestamp", "unknown").replace(":", "").replace("-", "")
                output_path = self.export_dir / f"import_{timestamp}.py"
            
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, 'w') as f:
                f.write(script)
            
            app_logger.info(f"ReaScript saved to: {output_path}")
            return output_path
        except Exception as e:
            app_logger.error(f"Error saving ReaScript: {e}")
            return None
    
    def _create_reaper_script(self, export_data):
        """
        Create complete REAPER ReaScript content with all track creation logic.
        """
        audio_track = export_data.get("audio_track", {})
        video_track = export_data.get("video_track", {})
        enhancement_tracks = export_data.get("enhancement_tracks", [])
        
        audio_file = audio_track.get("file", "")
        video_file = video_track.get("file", "")
        noise_strength = audio_track.get("processing", {}).get("noise_reduction", {}).get("strength", 0.5)
        
        enhancement_code = ""
        for i, track_info in enumerate(enhancement_tracks):
            file_path = track_info.get("file", "").replace("\\", "\\\\")
            name = track_info.get("name", f"Enhancement {i}").replace('"', '\\"')
            start_time = track_info.get("start_time", 0)
            duration = track_info.get("duration", 10)
            volume = track_info.get("volume", 1.0)
            fade_in = track_info.get("fade_in", 0.5)
            fade_out = track_info.get("fade_out", 0.5)
            
            enhancement_code += f'''
    # Create enhancement track {i + 1}
    RPR_InsertTrackAtIndex({i + 2}, False)
    track = RPR_GetTrack(project, {i + 2})
    RPR_GetSetMediaTrackInfo_String(track, "P_NAME", "{name}", True)
    
    # Add media item
    item = RPR_AddMediaItemToTrack(track)
    take = RPR_GetActiveTake(item)
    source = RPR_PCM_Source_CreateFromFile("{file_path}")
    RPR_SetMediaItemTake_Source(take, source)
    
    # Set timing
    RPR_SetMediaItemInfo_Value(item, "D_POSITION", {start_time})
    RPR_SetMediaItemInfo_Value(item, "D_LENGTH", {duration})
    
    # Set volume
    RPR_SetMediaTrackInfo_Value(track, "D_VOL", {volume})
    
    # Set fades
    RPR_SetMediaItemInfo_Value(item, "D_FADEINLEN", {fade_in})
    RPR_SetMediaItemInfo_Value(item, "D_FADEOUTLEN", {fade_out})
'''
        
        script = f'''#!/usr/bin/env python3
# REAPER Audio Enhancement Import Script
# Auto-generated by Audio Enhancement Tool
# Run this script in REAPER's Script Editor (Actions > Show Console)

def main():
    """Import audio enhancement results into REAPER."""
    
    # Get current project
    project = RPR_EnumProjects(-1)
    
    # Create original audio track
    RPR_InsertTrackAtIndex(0, False)
    audio_track = RPR_GetTrack(project, 0)
    RPR_GetSetMediaTrackInfo_String(audio_track, "P_NAME", "Original Audio", True)
    
    # Add audio file
    audio_item = RPR_AddMediaItemToTrack(audio_track)
    audio_take = RPR_GetActiveTake(audio_item)
    audio_source = RPR_PCM_Source_CreateFromFile("{audio_file.replace(chr(92), chr(92)*2)}")
    RPR_SetMediaItemTake_Source(audio_take, audio_source)
    
    # Set audio item length to match audio file duration
    audio_source_length = RPR_GetMediaSourceLength(audio_source)
    RPR_SetMediaItemLength(audio_item, audio_source_length, False)
    
    # Apply noise reduction (as a note - actual FX application requires more complex setup)
    # Noise reduction strength: {noise_strength}
    
    # Create video track
    RPR_InsertTrackAtIndex(1, False)
    video_track = RPR_GetTrack(project, 1)
    RPR_GetSetMediaTrackInfo_String(video_track, "P_NAME", "Video", True)
    
    # Add video file
    video_item = RPR_AddMediaItemToTrack(video_track)
    video_take = RPR_GetActiveTake(video_item)
    video_source = RPR_PCM_Source_CreateFromFile("{video_file.replace(chr(92), chr(92)*2)}")
    RPR_SetMediaItemTake_Source(video_take, video_source)
    
    # Set video item length to match video file duration
    video_source_length = RPR_GetMediaSourceLength(video_source)
    RPR_SetMediaItemLength(video_item, video_source_length, False)
    
    # Mute video track so only enhancement audio plays
    RPR_SetMediaTrackInfo_Value(video_track, "B_MUTE", 1)
{enhancement_code}
    
    # Refresh UI
    RPR_UpdateArrange()
    
    print("✓ Audio enhancement import complete!")
    print(f"Created {{len(enhancement_tracks) + 2}} tracks")

if __name__ == "__main__":
    main()
'''
        return script
